//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwUtils.PostApi {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/custom-duty-info/data")]
    public partial class CustomDutyEventsForMailFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CustomDutyEventsForMailErrors errorIDField;
        
        private bool errorIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CustomDutyEventsForMailErrors ErrorID {
            get {
                return this.errorIDField;
            }
            set {
                this.errorIDField = value;
                this.RaisePropertyChanged("ErrorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorIDSpecified {
            get {
                return this.errorIDFieldSpecified;
            }
            set {
                this.errorIDFieldSpecified = value;
                this.RaisePropertyChanged("ErrorIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/custom-duty-info/data")]
    public enum CustomDutyEventsForMailErrors {
        
        /// <remarks/>
        BarcodeIsNull,
        
        /// <remarks/>
        InternalServiceError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/custom-duty-info/data")]
    public partial class CustomDutyEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberField;
        
        private System.DateTime eventDateTimeField;
        
        private bool eventDateTimeFieldSpecified;
        
        private string eventTypeField;
        
        private string eventNameField;
        
        private string indexToField;
        
        private string indexEventField;
        
        private string countryEventCodeField;
        
        private string countryToCodeField;
        
        private string sumPaymentForwardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EventDateTime {
            get {
                return this.eventDateTimeField;
            }
            set {
                this.eventDateTimeField = value;
                this.RaisePropertyChanged("EventDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventDateTimeSpecified {
            get {
                return this.eventDateTimeFieldSpecified;
            }
            set {
                this.eventDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("EventDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string EventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
                this.RaisePropertyChanged("EventType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
                this.RaisePropertyChanged("EventName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IndexTo {
            get {
                return this.indexToField;
            }
            set {
                this.indexToField = value;
                this.RaisePropertyChanged("IndexTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IndexEvent {
            get {
                return this.indexEventField;
            }
            set {
                this.indexEventField = value;
                this.RaisePropertyChanged("IndexEvent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryEventCode {
            get {
                return this.countryEventCodeField;
            }
            set {
                this.countryEventCodeField = value;
                this.RaisePropertyChanged("CountryEventCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryToCode {
            get {
                return this.countryToCodeField;
            }
            set {
                this.countryToCodeField = value;
                this.RaisePropertyChanged("CountryToCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string SumPaymentForward {
            get {
                return this.sumPaymentForwardField;
            }
            set {
                this.sumPaymentForwardField = value;
                this.RaisePropertyChanged("SumPaymentForward");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/custom-duty-info/data")]
    public partial class CustomDutyEventsForMailInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barcodeField;
        
        private string languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("Barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class UserParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Rtm02Parameter sendCtgField;
        
        private string sndrField;
        
        private string rcpnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Rtm02Parameter SendCtg {
            get {
                return this.sendCtgField;
            }
            set {
                this.sendCtgField = value;
                this.RaisePropertyChanged("SendCtg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sndr {
            get {
                return this.sndrField;
            }
            set {
                this.sndrField = value;
                this.RaisePropertyChanged("Sndr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Rcpn {
            get {
                return this.rcpnField;
            }
            set {
                this.rcpnField = value;
                this.RaisePropertyChanged("Rcpn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class Rtm02Parameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class OperationParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Rtm02Parameter operTypeField;
        
        private Rtm02Parameter operAttrField;
        
        private System.DateTime operDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Rtm02Parameter OperType {
            get {
                return this.operTypeField;
            }
            set {
                this.operTypeField = value;
                this.RaisePropertyChanged("OperType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Rtm02Parameter OperAttr {
            get {
                return this.operAttrField;
            }
            set {
                this.operAttrField = value;
                this.RaisePropertyChanged("OperAttr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime OperDate {
            get {
                return this.operDateField;
            }
            set {
                this.operDateField = value;
                this.RaisePropertyChanged("OperDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class ItemParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barcodeField;
        
        private string internumField;
        
        private bool validRuTypeField;
        
        private bool validEnTypeField;
        
        private string complexItemNameField;
        
        private Rtm02Parameter mailRankField;
        
        private Rtm02Parameter postMarkField;
        
        private Rtm02Parameter mailTypeField;
        
        private Rtm02Parameter mailCtgField;
        
        private string massField;
        
        private string maxMassRUField;
        
        private string maxMassENField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("Barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Internum {
            get {
                return this.internumField;
            }
            set {
                this.internumField = value;
                this.RaisePropertyChanged("Internum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ValidRuType {
            get {
                return this.validRuTypeField;
            }
            set {
                this.validRuTypeField = value;
                this.RaisePropertyChanged("ValidRuType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ValidEnType {
            get {
                return this.validEnTypeField;
            }
            set {
                this.validEnTypeField = value;
                this.RaisePropertyChanged("ValidEnType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ComplexItemName {
            get {
                return this.complexItemNameField;
            }
            set {
                this.complexItemNameField = value;
                this.RaisePropertyChanged("ComplexItemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Rtm02Parameter MailRank {
            get {
                return this.mailRankField;
            }
            set {
                this.mailRankField = value;
                this.RaisePropertyChanged("MailRank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Rtm02Parameter PostMark {
            get {
                return this.postMarkField;
            }
            set {
                this.postMarkField = value;
                this.RaisePropertyChanged("PostMark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Rtm02Parameter MailType {
            get {
                return this.mailTypeField;
            }
            set {
                this.mailTypeField = value;
                this.RaisePropertyChanged("MailType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Rtm02Parameter MailCtg {
            get {
                return this.mailCtgField;
            }
            set {
                this.mailCtgField = value;
                this.RaisePropertyChanged("MailCtg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=9)]
        public string Mass {
            get {
                return this.massField;
            }
            set {
                this.massField = value;
                this.RaisePropertyChanged("Mass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=10)]
        public string MaxMassRU {
            get {
                return this.maxMassRUField;
            }
            set {
                this.maxMassRUField = value;
                this.RaisePropertyChanged("MaxMassRU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=11)]
        public string MaxMassEN {
            get {
                return this.maxMassENField;
            }
            set {
                this.maxMassENField = value;
                this.RaisePropertyChanged("MaxMassEN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class FinanceParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paymentField;
        
        private string valueField;
        
        private string massRateField;
        
        private string insrRateField;
        
        private string airRateField;
        
        private string rateField;
        
        private string customDutyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
                this.RaisePropertyChanged("Payment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string MassRate {
            get {
                return this.massRateField;
            }
            set {
                this.massRateField = value;
                this.RaisePropertyChanged("MassRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string InsrRate {
            get {
                return this.insrRateField;
            }
            set {
                this.insrRateField = value;
                this.RaisePropertyChanged("InsrRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string AirRate {
            get {
                return this.airRateField;
            }
            set {
                this.airRateField = value;
                this.RaisePropertyChanged("AirRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("Rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=6)]
        public string CustomDuty {
            get {
                return this.customDutyField;
            }
            set {
                this.customDutyField = value;
                this.RaisePropertyChanged("CustomDuty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class Country : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string code2AField;
        
        private string code3AField;
        
        private string nameField;
        
        private string nameRUField;
        
        private string nameENField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code2A {
            get {
                return this.code2AField;
            }
            set {
                this.code2AField = value;
                this.RaisePropertyChanged("Code2A");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Code3A {
            get {
                return this.code3AField;
            }
            set {
                this.code3AField = value;
                this.RaisePropertyChanged("Code3A");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NameRU {
            get {
                return this.nameRUField;
            }
            set {
                this.nameRUField = value;
                this.RaisePropertyChanged("NameRU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NameEN {
            get {
                return this.nameENField;
            }
            set {
                this.nameENField = value;
                this.RaisePropertyChanged("NameEN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string indexField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
                this.RaisePropertyChanged("Index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class AddressParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Address destinationAddressField;
        
        private Address operationAddressField;
        
        private Country mailDirectField;
        
        private Country countryFromField;
        
        private Country countryOperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Address DestinationAddress {
            get {
                return this.destinationAddressField;
            }
            set {
                this.destinationAddressField = value;
                this.RaisePropertyChanged("DestinationAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Address OperationAddress {
            get {
                return this.operationAddressField;
            }
            set {
                this.operationAddressField = value;
                this.RaisePropertyChanged("OperationAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Country MailDirect {
            get {
                return this.mailDirectField;
            }
            set {
                this.mailDirectField = value;
                this.RaisePropertyChanged("MailDirect");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Country CountryFrom {
            get {
                return this.countryFromField;
            }
            set {
                this.countryFromField = value;
                this.RaisePropertyChanged("CountryFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Country CountryOper {
            get {
                return this.countryOperField;
            }
            set {
                this.countryOperField = value;
                this.RaisePropertyChanged("CountryOper");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/operationhistory/data")]
    public partial class OperationHistoryRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddressParameters addressParametersField;
        
        private FinanceParameters financeParametersField;
        
        private ItemParameters itemParametersField;
        
        private OperationParameters operationParametersField;
        
        private UserParameters userParametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AddressParameters AddressParameters {
            get {
                return this.addressParametersField;
            }
            set {
                this.addressParametersField = value;
                this.RaisePropertyChanged("AddressParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FinanceParameters FinanceParameters {
            get {
                return this.financeParametersField;
            }
            set {
                this.financeParametersField = value;
                this.RaisePropertyChanged("FinanceParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ItemParameters ItemParameters {
            get {
                return this.itemParametersField;
            }
            set {
                this.itemParametersField = value;
                this.RaisePropertyChanged("ItemParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public OperationParameters OperationParameters {
            get {
                return this.operationParametersField;
            }
            set {
                this.operationParametersField = value;
                this.RaisePropertyChanged("OperationParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public UserParameters UserParameters {
            get {
                return this.userParametersField;
            }
            set {
                this.userParametersField = value;
                this.RaisePropertyChanged("UserParameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public partial class PostalOrderEventsForMailError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PostalOrderEventsForMailErrors errorIDField;
        
        private bool errorIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PostalOrderEventsForMailErrors ErrorID {
            get {
                return this.errorIDField;
            }
            set {
                this.errorIDField = value;
                this.RaisePropertyChanged("ErrorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorIDSpecified {
            get {
                return this.errorIDFieldSpecified;
            }
            set {
                this.errorIDFieldSpecified = value;
                this.RaisePropertyChanged("ErrorIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public enum PostalOrderEventsForMailErrors {
        
        /// <remarks/>
        InvalidLoginOrPassword,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://russianpost.org/operationhistory", ConfigurationName="PostApi.OperationHistory12")]
    public interface OperationHistory12 {
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения (http://russianpost.org/operationhistory/data) не соответствует значению по умолчанию (http://russianpost.org/operationhistory).
        [System.ServiceModel.OperationContractAttribute(Action="http://russianpost.org/operationhistory/OperationHistory12/getOperationHistoryReq" +
            "uest", ReplyAction="http://russianpost.org/operationhistory/OperationHistory12/getOperationHistoryRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://russianpost.org/operationhistory/OperationHistory12/getOperationHistory/Fa" +
            "ult/OperationHistoryFault", Name="OperationHistoryFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://russianpost.org/operationhistory/OperationHistory12/getOperationHistory/Fa" +
            "ult/AuthorizationFault", Name="AuthorizationFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OperationHistoryData")]
        DwUtils.PostApi.getOperationHistoryResponse getOperationHistory(DwUtils.PostApi.getOperationHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://russianpost.org/operationhistory/OperationHistory12/getOperationHistoryReq" +
            "uest", ReplyAction="http://russianpost.org/operationhistory/OperationHistory12/getOperationHistoryRes" +
            "ponse")]
        System.Threading.Tasks.Task<DwUtils.PostApi.getOperationHistoryResponse> getOperationHistoryAsync(DwUtils.PostApi.getOperationHistoryRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения (http://russianpost.org/operationhistory/data) не соответствует значению по умолчанию (http://russianpost.org/operationhistory).
        [System.ServiceModel.OperationContractAttribute(Action="http://russianpost.org/operationhistory/OperationHistory12/getLanguagesRequest", ReplyAction="http://russianpost.org/operationhistory/OperationHistory12/getLanguagesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://russianpost.org/operationhistory/OperationHistory12/getLanguages/Fault/Ope" +
            "rationHistoryFault", Name="OperationHistoryFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://russianpost.org/operationhistory/OperationHistory12/getLanguages/Fault/Aut" +
            "horizationFault", Name="AuthorizationFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://russianpost.org/operationhistory/OperationHistory12/getLanguages/Fault/Lan" +
            "guageFault", Name="LanguageFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="LanguageData")]
        DwUtils.PostApi.getLanguagesResponse getLanguages(DwUtils.PostApi.getLanguagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://russianpost.org/operationhistory/OperationHistory12/getLanguagesRequest", ReplyAction="http://russianpost.org/operationhistory/OperationHistory12/getLanguagesResponse")]
        System.Threading.Tasks.Task<DwUtils.PostApi.getLanguagesResponse> getLanguagesAsync(DwUtils.PostApi.getLanguagesRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения (http://www.russianpost.org/custom-duty-info/data) не соответствует значению по умолчанию (http://russianpost.org/operationhistory).
        [System.ServiceModel.OperationContractAttribute(Action="http://russianpost.org/operationhistory/OperationHistory12/getCustomDutyEventsFor" +
            "MailRequest", ReplyAction="http://russianpost.org/operationhistory/OperationHistory12/getCustomDutyEventsFor" +
            "MailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DwUtils.PostApi.CustomDutyEventsForMailFault), Action="http://russianpost.org/operationhistory/OperationHistory12/getCustomDutyEventsFor" +
            "Mail/Fault/CustomDutyEventsForMailFault", Name="CustomDutyEventsForMailFault", Namespace="http://www.russianpost.org/custom-duty-info/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://russianpost.org/operationhistory/OperationHistory12/getCustomDutyEventsFor" +
            "Mail/Fault/AuthorizationFault", Name="AuthorizationFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://russianpost.org/operationhistory/OperationHistory12/getCustomDutyEventsFor" +
            "Mail/Fault/LanguageFault", Name="LanguageFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CustomDutyEventsForMailOutput")]
        DwUtils.PostApi.getCustomDutyEventsForMailResponse getCustomDutyEventsForMail(DwUtils.PostApi.getCustomDutyEventsForMailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://russianpost.org/operationhistory/OperationHistory12/getCustomDutyEventsFor" +
            "MailRequest", ReplyAction="http://russianpost.org/operationhistory/OperationHistory12/getCustomDutyEventsFor" +
            "MailResponse")]
        System.Threading.Tasks.Task<DwUtils.PostApi.getCustomDutyEventsForMailResponse> getCustomDutyEventsForMailAsync(DwUtils.PostApi.getCustomDutyEventsForMailRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения (http://russianpost.org/sms-info/data) не соответствует значению по умолчанию (http://russianpost.org/operationhistory).
        [System.ServiceModel.OperationContractAttribute(Action="http://russianpost.org/operationhistory/OperationHistory12/getSmsHistoryRequest", ReplyAction="http://russianpost.org/operationhistory/OperationHistory12/getSmsHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://russianpost.org/operationhistory/OperationHistory12/getSmsHistory/Fault/Sm" +
            "sHistoryFault", Name="SmsHistoryFaultReason", Namespace="http://russianpost.org/sms-info/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://russianpost.org/operationhistory/OperationHistory12/getSmsHistory/Fault/Au" +
            "thorizationFault", Name="AuthorizationFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://russianpost.org/operationhistory/OperationHistory12/getSmsHistory/Fault/La" +
            "nguageFault", Name="LanguageFaultReason", Namespace="http://russianpost.org/operationhistory/data")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SmsHistoryData")]
        DwUtils.PostApi.getSmsHistoryResponse getSmsHistory(DwUtils.PostApi.getSmsHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://russianpost.org/operationhistory/OperationHistory12/getSmsHistoryRequest", ReplyAction="http://russianpost.org/operationhistory/OperationHistory12/getSmsHistoryResponse")]
        System.Threading.Tasks.Task<DwUtils.PostApi.getSmsHistoryResponse> getSmsHistoryAsync(DwUtils.PostApi.getSmsHistoryRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения (http://www.russianpost.org/RTM/DataExchangeESPP/Data) не соответствует значению по умолчанию (http://russianpost.org/operationhistory).
        [System.ServiceModel.OperationContractAttribute(Action="http://russianpost.org/operationhistory/OperationHistory12/PostalOrderEventsForMa" +
            "ilRequest", ReplyAction="http://russianpost.org/operationhistory/OperationHistory12/PostalOrderEventsForMa" +
            "ilResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DwUtils.PostApi.PostalOrderEventsForMailError[]), Action="http://russianpost.org/operationhistory/OperationHistory12/PostalOrderEventsForMa" +
            "il/Fault/PostalOrderEventsForMailFault", Name="PostalOrderEventsForMailFault", Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PostalOrderEventsForMaiOutput")]
        DwUtils.PostApi.PostalOrderEventsForMailResponse PostalOrderEventsForMail(DwUtils.PostApi.PostalOrderEventsForMailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://russianpost.org/operationhistory/OperationHistory12/PostalOrderEventsForMa" +
            "ilRequest", ReplyAction="http://russianpost.org/operationhistory/OperationHistory12/PostalOrderEventsForMa" +
            "ilResponse")]
        System.Threading.Tasks.Task<DwUtils.PostApi.PostalOrderEventsForMailResponse> PostalOrderEventsForMailAsync(DwUtils.PostApi.PostalOrderEventsForMailRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://russianpost.org/operationhistory/data")]
    public partial class OperationHistoryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barcodeField;
        
        private int messageTypeField;
        
        private string languageField;
        
        public OperationHistoryRequest() {
            this.languageField = "RUS";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("Barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute("RUS")]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://russianpost.org/operationhistory/data")]
    public partial class AuthorizationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passwordField;
        
        private string mustUnderstandField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.xmlsoap.org/soap/envelope/")]
        public string mustUnderstand {
            get {
                return this.mustUnderstandField;
            }
            set {
                this.mustUnderstandField = value;
                this.RaisePropertyChanged("mustUnderstand");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOperationHistory", WrapperNamespace="http://russianpost.org/operationhistory", IsWrapped=true)]
    public partial class getOperationHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/operationhistory/data", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/operationhistory/data")]
        public DwUtils.PostApi.OperationHistoryRequest OperationHistoryRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/operationhistory/data", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/operationhistory/data")]
        public DwUtils.PostApi.AuthorizationHeader AuthorizationHeader;
        
        public getOperationHistoryRequest() {
        }
        
        public getOperationHistoryRequest(DwUtils.PostApi.OperationHistoryRequest OperationHistoryRequest, DwUtils.PostApi.AuthorizationHeader AuthorizationHeader) {
            this.OperationHistoryRequest = OperationHistoryRequest;
            this.AuthorizationHeader = AuthorizationHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOperationHistoryResponse", WrapperNamespace="http://russianpost.org/operationhistory", IsWrapped=true)]
    public partial class getOperationHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/operationhistory/data", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://russianpost.org/operationhistory/data")]
        [System.Xml.Serialization.XmlArrayItemAttribute("historyRecord")]
        public DwUtils.PostApi.OperationHistoryRecord[] OperationHistoryData;
        
        public getOperationHistoryResponse() {
        }
        
        public getOperationHistoryResponse(DwUtils.PostApi.OperationHistoryRecord[] OperationHistoryData) {
            this.OperationHistoryData = OperationHistoryData;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://russianpost.org/operationhistory/data")]
    public partial class LanguageDataLanguage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLanguages", WrapperNamespace="http://russianpost.org/operationhistory", IsWrapped=true)]
    public partial class getLanguagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/operationhistory/data", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/operationhistory/data")]
        public DwUtils.PostApi.AuthorizationHeader AuthorizationHeader;
        
        public getLanguagesRequest() {
        }
        
        public getLanguagesRequest(DwUtils.PostApi.AuthorizationHeader AuthorizationHeader) {
            this.AuthorizationHeader = AuthorizationHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLanguagesResponse", WrapperNamespace="http://russianpost.org/operationhistory", IsWrapped=true)]
    public partial class getLanguagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/operationhistory/data", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://russianpost.org/operationhistory/data")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Language", IsNullable=false)]
        public DwUtils.PostApi.LanguageDataLanguage[] LanguageData;
        
        public getLanguagesResponse() {
        }
        
        public getLanguagesResponse(DwUtils.PostApi.LanguageDataLanguage[] LanguageData) {
            this.LanguageData = LanguageData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomDutyEventsForMail", WrapperNamespace="http://russianpost.org/operationhistory", IsWrapped=true)]
    public partial class getCustomDutyEventsForMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/operationhistory/data", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/operationhistory/data")]
        public DwUtils.PostApi.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.russianpost.org/custom-duty-info/data", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.russianpost.org/custom-duty-info/data")]
        public DwUtils.PostApi.CustomDutyEventsForMailInput CustomDutyEventsForMailInput;
        
        public getCustomDutyEventsForMailRequest() {
        }
        
        public getCustomDutyEventsForMailRequest(DwUtils.PostApi.AuthorizationHeader AuthorizationHeader, DwUtils.PostApi.CustomDutyEventsForMailInput CustomDutyEventsForMailInput) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.CustomDutyEventsForMailInput = CustomDutyEventsForMailInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomDutyEventsForMailResponse", WrapperNamespace="http://russianpost.org/operationhistory", IsWrapped=true)]
    public partial class getCustomDutyEventsForMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.russianpost.org/custom-duty-info/data", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.russianpost.org/custom-duty-info/data")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DwUtils.PostApi.CustomDutyEvent[] CustomDutyEventsForMailOutput;
        
        public getCustomDutyEventsForMailResponse() {
        }
        
        public getCustomDutyEventsForMailResponse(DwUtils.PostApi.CustomDutyEvent[] CustomDutyEventsForMailOutput) {
            this.CustomDutyEventsForMailOutput = CustomDutyEventsForMailOutput;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://russianpost.org/sms-info/data")]
    public partial class SmsHistoryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barcodeField;
        
        private string languageField;
        
        public SmsHistoryRequest() {
            this.languageField = "RUS";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("Barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute("RUS")]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://russianpost.org/sms-info/data")]
    public partial class SmsHistoryRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string numberField;
        
        private string notificationTypeIDField;
        
        private string notificationTypeNameField;
        
        private string notificationStatusIDField;
        
        private string notificationStatusNameField;
        
        private System.DateTime notificationStatusDateField;
        
        private string sendedIDField;
        
        private string sourceOperationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string NotificationTypeID {
            get {
                return this.notificationTypeIDField;
            }
            set {
                this.notificationTypeIDField = value;
                this.RaisePropertyChanged("NotificationTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NotificationTypeName {
            get {
                return this.notificationTypeNameField;
            }
            set {
                this.notificationTypeNameField = value;
                this.RaisePropertyChanged("NotificationTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string NotificationStatusID {
            get {
                return this.notificationStatusIDField;
            }
            set {
                this.notificationStatusIDField = value;
                this.RaisePropertyChanged("NotificationStatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NotificationStatusName {
            get {
                return this.notificationStatusNameField;
            }
            set {
                this.notificationStatusNameField = value;
                this.RaisePropertyChanged("NotificationStatusName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime NotificationStatusDate {
            get {
                return this.notificationStatusDateField;
            }
            set {
                this.notificationStatusDateField = value;
                this.RaisePropertyChanged("NotificationStatusDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string SendedID {
            get {
                return this.sendedIDField;
            }
            set {
                this.sendedIDField = value;
                this.RaisePropertyChanged("SendedID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SourceOperation {
            get {
                return this.sourceOperationField;
            }
            set {
                this.sourceOperationField = value;
                this.RaisePropertyChanged("SourceOperation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsHistory", WrapperNamespace="http://russianpost.org/operationhistory", IsWrapped=true)]
    public partial class getSmsHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/operationhistory/data", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/operationhistory/data")]
        public DwUtils.PostApi.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/sms-info/data", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/sms-info/data")]
        public DwUtils.PostApi.SmsHistoryRequest SmsHistoryRequest;
        
        public getSmsHistoryRequest() {
        }
        
        public getSmsHistoryRequest(DwUtils.PostApi.AuthorizationHeader AuthorizationHeader, DwUtils.PostApi.SmsHistoryRequest SmsHistoryRequest) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.SmsHistoryRequest = SmsHistoryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsHistoryResponse", WrapperNamespace="http://russianpost.org/operationhistory", IsWrapped=true)]
    public partial class getSmsHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/sms-info/data", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://russianpost.org/sms-info/data")]
        [System.Xml.Serialization.XmlArrayItemAttribute("historyRecord")]
        public DwUtils.PostApi.SmsHistoryRecord[] SmsHistoryData;
        
        public getSmsHistoryResponse() {
        }
        
        public getSmsHistoryResponse(DwUtils.PostApi.SmsHistoryRecord[] SmsHistoryData) {
            this.SmsHistoryData = SmsHistoryData;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public partial class PostalOrderEventsForMailInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barcodeField;
        
        private string languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("Barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
    public partial class PostalOrderEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numberField;
        
        private System.DateTime eventDateTimeField;
        
        private bool eventDateTimeFieldSpecified;
        
        private string eventTypeField;
        
        private string eventNameField;
        
        private string indexToField;
        
        private string indexEventField;
        
        private string sumPaymentForwardField;
        
        private string countryEventCodeField;
        
        private string countryToCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EventDateTime {
            get {
                return this.eventDateTimeField;
            }
            set {
                this.eventDateTimeField = value;
                this.RaisePropertyChanged("EventDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EventDateTimeSpecified {
            get {
                return this.eventDateTimeFieldSpecified;
            }
            set {
                this.eventDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("EventDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string EventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
                this.RaisePropertyChanged("EventType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
                this.RaisePropertyChanged("EventName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string IndexTo {
            get {
                return this.indexToField;
            }
            set {
                this.indexToField = value;
                this.RaisePropertyChanged("IndexTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string IndexEvent {
            get {
                return this.indexEventField;
            }
            set {
                this.indexEventField = value;
                this.RaisePropertyChanged("IndexEvent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string SumPaymentForward {
            get {
                return this.sumPaymentForwardField;
            }
            set {
                this.sumPaymentForwardField = value;
                this.RaisePropertyChanged("SumPaymentForward");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryEventCode {
            get {
                return this.countryEventCodeField;
            }
            set {
                this.countryEventCodeField = value;
                this.RaisePropertyChanged("CountryEventCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryToCode {
            get {
                return this.countryToCodeField;
            }
            set {
                this.countryToCodeField = value;
                this.RaisePropertyChanged("CountryToCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostalOrderEventsForMail", WrapperNamespace="http://russianpost.org/operationhistory", IsWrapped=true)]
    public partial class PostalOrderEventsForMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://russianpost.org/operationhistory/data", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://russianpost.org/operationhistory/data")]
        public DwUtils.PostApi.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
        public DwUtils.PostApi.PostalOrderEventsForMailInput PostalOrderEventsForMailInput;
        
        public PostalOrderEventsForMailRequest() {
        }
        
        public PostalOrderEventsForMailRequest(DwUtils.PostApi.AuthorizationHeader AuthorizationHeader, DwUtils.PostApi.PostalOrderEventsForMailInput PostalOrderEventsForMailInput) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.PostalOrderEventsForMailInput = PostalOrderEventsForMailInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostalOrderEventsForMailResponse", WrapperNamespace="http://russianpost.org/operationhistory", IsWrapped=true)]
    public partial class PostalOrderEventsForMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.russianpost.org/RTM/DataExchangeESPP/Data")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DwUtils.PostApi.PostalOrderEvent[] PostalOrderEventsForMaiOutput;
        
        public PostalOrderEventsForMailResponse() {
        }
        
        public PostalOrderEventsForMailResponse(DwUtils.PostApi.PostalOrderEvent[] PostalOrderEventsForMaiOutput) {
            this.PostalOrderEventsForMaiOutput = PostalOrderEventsForMaiOutput;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OperationHistory12Channel : DwUtils.PostApi.OperationHistory12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperationHistory12Client : System.ServiceModel.ClientBase<DwUtils.PostApi.OperationHistory12>, DwUtils.PostApi.OperationHistory12 {
        
        public OperationHistory12Client() {
        }
        
        public OperationHistory12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperationHistory12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationHistory12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationHistory12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DwUtils.PostApi.getOperationHistoryResponse DwUtils.PostApi.OperationHistory12.getOperationHistory(DwUtils.PostApi.getOperationHistoryRequest request) {
            return base.Channel.getOperationHistory(request);
        }
        
        public DwUtils.PostApi.OperationHistoryRecord[] getOperationHistory(DwUtils.PostApi.OperationHistoryRequest OperationHistoryRequest, DwUtils.PostApi.AuthorizationHeader AuthorizationHeader) {
            DwUtils.PostApi.getOperationHistoryRequest inValue = new DwUtils.PostApi.getOperationHistoryRequest();
            inValue.OperationHistoryRequest = OperationHistoryRequest;
            inValue.AuthorizationHeader = AuthorizationHeader;
            DwUtils.PostApi.getOperationHistoryResponse retVal = ((DwUtils.PostApi.OperationHistory12)(this)).getOperationHistory(inValue);
            return retVal.OperationHistoryData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DwUtils.PostApi.getOperationHistoryResponse> DwUtils.PostApi.OperationHistory12.getOperationHistoryAsync(DwUtils.PostApi.getOperationHistoryRequest request) {
            return base.Channel.getOperationHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<DwUtils.PostApi.getOperationHistoryResponse> getOperationHistoryAsync(DwUtils.PostApi.OperationHistoryRequest OperationHistoryRequest, DwUtils.PostApi.AuthorizationHeader AuthorizationHeader) {
            DwUtils.PostApi.getOperationHistoryRequest inValue = new DwUtils.PostApi.getOperationHistoryRequest();
            inValue.OperationHistoryRequest = OperationHistoryRequest;
            inValue.AuthorizationHeader = AuthorizationHeader;
            return ((DwUtils.PostApi.OperationHistory12)(this)).getOperationHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DwUtils.PostApi.getLanguagesResponse DwUtils.PostApi.OperationHistory12.getLanguages(DwUtils.PostApi.getLanguagesRequest request) {
            return base.Channel.getLanguages(request);
        }
        
        public DwUtils.PostApi.LanguageDataLanguage[] getLanguages(DwUtils.PostApi.AuthorizationHeader AuthorizationHeader) {
            DwUtils.PostApi.getLanguagesRequest inValue = new DwUtils.PostApi.getLanguagesRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            DwUtils.PostApi.getLanguagesResponse retVal = ((DwUtils.PostApi.OperationHistory12)(this)).getLanguages(inValue);
            return retVal.LanguageData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DwUtils.PostApi.getLanguagesResponse> DwUtils.PostApi.OperationHistory12.getLanguagesAsync(DwUtils.PostApi.getLanguagesRequest request) {
            return base.Channel.getLanguagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DwUtils.PostApi.getLanguagesResponse> getLanguagesAsync(DwUtils.PostApi.AuthorizationHeader AuthorizationHeader) {
            DwUtils.PostApi.getLanguagesRequest inValue = new DwUtils.PostApi.getLanguagesRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            return ((DwUtils.PostApi.OperationHistory12)(this)).getLanguagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DwUtils.PostApi.getCustomDutyEventsForMailResponse DwUtils.PostApi.OperationHistory12.getCustomDutyEventsForMail(DwUtils.PostApi.getCustomDutyEventsForMailRequest request) {
            return base.Channel.getCustomDutyEventsForMail(request);
        }
        
        public DwUtils.PostApi.CustomDutyEvent[] getCustomDutyEventsForMail(DwUtils.PostApi.AuthorizationHeader AuthorizationHeader, DwUtils.PostApi.CustomDutyEventsForMailInput CustomDutyEventsForMailInput) {
            DwUtils.PostApi.getCustomDutyEventsForMailRequest inValue = new DwUtils.PostApi.getCustomDutyEventsForMailRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.CustomDutyEventsForMailInput = CustomDutyEventsForMailInput;
            DwUtils.PostApi.getCustomDutyEventsForMailResponse retVal = ((DwUtils.PostApi.OperationHistory12)(this)).getCustomDutyEventsForMail(inValue);
            return retVal.CustomDutyEventsForMailOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DwUtils.PostApi.getCustomDutyEventsForMailResponse> DwUtils.PostApi.OperationHistory12.getCustomDutyEventsForMailAsync(DwUtils.PostApi.getCustomDutyEventsForMailRequest request) {
            return base.Channel.getCustomDutyEventsForMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<DwUtils.PostApi.getCustomDutyEventsForMailResponse> getCustomDutyEventsForMailAsync(DwUtils.PostApi.AuthorizationHeader AuthorizationHeader, DwUtils.PostApi.CustomDutyEventsForMailInput CustomDutyEventsForMailInput) {
            DwUtils.PostApi.getCustomDutyEventsForMailRequest inValue = new DwUtils.PostApi.getCustomDutyEventsForMailRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.CustomDutyEventsForMailInput = CustomDutyEventsForMailInput;
            return ((DwUtils.PostApi.OperationHistory12)(this)).getCustomDutyEventsForMailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DwUtils.PostApi.getSmsHistoryResponse DwUtils.PostApi.OperationHistory12.getSmsHistory(DwUtils.PostApi.getSmsHistoryRequest request) {
            return base.Channel.getSmsHistory(request);
        }
        
        public DwUtils.PostApi.SmsHistoryRecord[] getSmsHistory(DwUtils.PostApi.AuthorizationHeader AuthorizationHeader, DwUtils.PostApi.SmsHistoryRequest SmsHistoryRequest) {
            DwUtils.PostApi.getSmsHistoryRequest inValue = new DwUtils.PostApi.getSmsHistoryRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.SmsHistoryRequest = SmsHistoryRequest;
            DwUtils.PostApi.getSmsHistoryResponse retVal = ((DwUtils.PostApi.OperationHistory12)(this)).getSmsHistory(inValue);
            return retVal.SmsHistoryData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DwUtils.PostApi.getSmsHistoryResponse> DwUtils.PostApi.OperationHistory12.getSmsHistoryAsync(DwUtils.PostApi.getSmsHistoryRequest request) {
            return base.Channel.getSmsHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<DwUtils.PostApi.getSmsHistoryResponse> getSmsHistoryAsync(DwUtils.PostApi.AuthorizationHeader AuthorizationHeader, DwUtils.PostApi.SmsHistoryRequest SmsHistoryRequest) {
            DwUtils.PostApi.getSmsHistoryRequest inValue = new DwUtils.PostApi.getSmsHistoryRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.SmsHistoryRequest = SmsHistoryRequest;
            return ((DwUtils.PostApi.OperationHistory12)(this)).getSmsHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DwUtils.PostApi.PostalOrderEventsForMailResponse DwUtils.PostApi.OperationHistory12.PostalOrderEventsForMail(DwUtils.PostApi.PostalOrderEventsForMailRequest request) {
            return base.Channel.PostalOrderEventsForMail(request);
        }
        
        public DwUtils.PostApi.PostalOrderEvent[] PostalOrderEventsForMail(DwUtils.PostApi.AuthorizationHeader AuthorizationHeader, DwUtils.PostApi.PostalOrderEventsForMailInput PostalOrderEventsForMailInput) {
            DwUtils.PostApi.PostalOrderEventsForMailRequest inValue = new DwUtils.PostApi.PostalOrderEventsForMailRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.PostalOrderEventsForMailInput = PostalOrderEventsForMailInput;
            DwUtils.PostApi.PostalOrderEventsForMailResponse retVal = ((DwUtils.PostApi.OperationHistory12)(this)).PostalOrderEventsForMail(inValue);
            return retVal.PostalOrderEventsForMaiOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DwUtils.PostApi.PostalOrderEventsForMailResponse> DwUtils.PostApi.OperationHistory12.PostalOrderEventsForMailAsync(DwUtils.PostApi.PostalOrderEventsForMailRequest request) {
            return base.Channel.PostalOrderEventsForMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<DwUtils.PostApi.PostalOrderEventsForMailResponse> PostalOrderEventsForMailAsync(DwUtils.PostApi.AuthorizationHeader AuthorizationHeader, DwUtils.PostApi.PostalOrderEventsForMailInput PostalOrderEventsForMailInput) {
            DwUtils.PostApi.PostalOrderEventsForMailRequest inValue = new DwUtils.PostApi.PostalOrderEventsForMailRequest();
            inValue.AuthorizationHeader = AuthorizationHeader;
            inValue.PostalOrderEventsForMailInput = PostalOrderEventsForMailInput;
            return ((DwUtils.PostApi.OperationHistory12)(this)).PostalOrderEventsForMailAsync(inValue);
        }
    }
}
